from __future__ import annotations

from typing import Any, Self

type IntoExpr = Expr | str | int | float | bool | None

def lit(value: Any) -> Expr: ...
def element() -> Expr: ...
def list() -> ExprListNameSpace: ...
def struct() -> ExprStructNameSpace: ...
def field(name: str) -> Expr: ...
def merge(*exprs: Expr) -> Expr: ...
def coalesce(*exprs: Expr) -> Expr: ...

class DataJson:
    def __init__(self, data: Any) -> None: ...
    def query(self, expr: Expr) -> Self: ...
    def collect(self) -> Any: ...

class ExprListNameSpace:
    def get(self, i: int) -> Expr: ...
    def slice(
        self,
        start: int | None = None,
        end: int | None = None,
        step: int | None = None,
    ) -> Expr: ...
    def flatten(self) -> Expr: ...
    def reverse(self) -> Expr: ...
    def sort(self) -> Expr: ...
    def sum(self) -> Expr: ...
    def min(self) -> Expr: ...
    def max(self) -> Expr: ...
    def avg(self) -> Expr: ...
    def length(self) -> Expr: ...
    def join(self, glue: str) -> Expr: ...
    def map(self, expr: Expr) -> Expr: ...
    def filter(self, cond: Expr) -> Expr: ...
    def contains(self, other: IntoExpr) -> Expr: ...
    def sort_by(self, key: Expr) -> Expr: ...
    def min_by(self, key: Expr) -> Expr: ...
    def max_by(self, key: Expr) -> Expr: ...

class ExprStrNameSpace:
    def length(self) -> Expr: ...
    def contains(self, other: str) -> Expr: ...
    def starts_with(self, other: str) -> Expr: ...
    def ends_with(self, other: str) -> Expr: ...
    def reverse(self) -> Expr: ...
    def slice(
        self,
        start: int | None = None,
        end: int | None = None,
        step: int | None = None,
    ) -> Expr: ...

class ExprStructNameSpace:
    def field(self, name: str) -> Expr: ...
    def keys(self) -> Expr: ...
    def values(self) -> Expr: ...

class Expr:
    @property
    def list(self) -> ExprListNameSpace: ...
    @property
    def str(self) -> ExprStrNameSpace: ...
    @property
    def struct(self) -> ExprStructNameSpace: ...
    def eq(self, other: IntoExpr) -> Self: ...
    def ne(self, other: IntoExpr) -> Self: ...
    def lt(self, other: IntoExpr) -> Self: ...
    def le(self, other: IntoExpr) -> Self: ...
    def gt(self, other: IntoExpr) -> Self: ...
    def ge(self, other: IntoExpr) -> Self: ...
    def and_(self, other: Expr) -> Self: ...
    def or_(self, other: Expr) -> Self: ...
    def not_(self) -> Self: ...
    def abs(self) -> Self: ...
    def ceil(self) -> Self: ...
    def floor(self) -> Self: ...
