from __future__ import annotations
from typing import Any, Self

type IntoExpr = Expr | str | int | float | bool | None

def key(name: str) -> Expr: ...
def select_list(*exprs: Expr) -> Expr: ...
def select_dict(**items: IntoExpr) -> Expr: ...
def lit(value: Any) -> Expr: ...
def element() -> Expr: ...
def merge(*exprs: Expr) -> Expr: ...
def not_null(*exprs: Expr) -> Expr: ...

class ExprListNameSpace:
    def get(self, i: int) -> Expr: ...
    def slice(
        self,
        start: int | None = None,
        end: int | None = None,
        step: int | None = None,
    ) -> Expr: ...
    def flatten(self) -> Expr: ...
    def reverse(self) -> Expr: ...
    def sort(self) -> Expr: ...
    def sum(self) -> Expr: ...
    def min(self) -> Expr: ...
    def max(self) -> Expr: ...
    def avg(self) -> Expr: ...
    def lengths(self) -> Expr: ...
    def join(self, glue: IntoExpr) -> Expr: ...
    def eval(self, expr: IntoExpr) -> Expr: ...
    def contains(self, other: IntoExpr) -> Expr: ...
    def filter(self, cond: IntoExpr) -> Expr: ...

class ExprStrNameSpace:
    def contains(self, other: IntoExpr) -> Expr: ...
    def starts_with(self, other: IntoExpr) -> Expr: ...
    def ends_with(self, other: IntoExpr) -> Expr: ...

class ExprStructNameSpace:
    def field(self, name: str) -> Expr: ...
    def keys(self) -> Expr: ...
    def values(self) -> Expr: ...

class Expr:
    @property
    def list(self) -> ExprListNameSpace: ...
    @property
    def str(self) -> ExprStrNameSpace: ...
    @property
    def struct(self) -> ExprStructNameSpace: ...
    def __getattr__(self, name: str) -> Self: ...  # type: ignore
    def field(self, name: str) -> Self: ...  # type: ignore
    def eq(self, other: IntoExpr) -> Self: ...
    def ne(self, other: IntoExpr) -> Self: ...
    def lt(self, other: IntoExpr) -> Self: ...
    def le(self, other: IntoExpr) -> Self: ...
    def gt(self, other: IntoExpr) -> Self: ...
    def ge(self, other: IntoExpr) -> Self: ...
    def and_(self, other: IntoExpr) -> Self: ...
    def or_(self, other: IntoExpr) -> Self: ...
    def not_(self) -> Self: ...
    def map(self, expr: IntoExpr) -> Self: ...
    def sort_by(self, key: IntoExpr) -> Self: ...
    def min_by(self, key: IntoExpr) -> Self: ...
    def max_by(self, key: IntoExpr) -> Self: ...
    def abs(self) -> Self: ...
    def avg(self) -> Self: ...
    def ceil(self) -> Self: ...
    def floor(self) -> Self: ...
    def search(self, data: Any) -> Any: ...
